# Generated by Django 2.0.7 on 2018-08-29 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20180730_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(blank=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('fee', models.IntegerField(blank=True)),
                ('paid', models.BooleanField(default=False)),
                ('distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Distributor')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Product')),
            ],
            options={
                'ordering': ('deadline',),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['deadline'], name='deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paid'], name='paid_idx'),
        ),
    ]
